name: SignLink
main: com.bergerkiller.bukkit.sl.SignLink
version: 1.23
author: bergerkiller
depend: [BKCommonLib]
description: Plugin that manages the display of variables on signs in various ways
commands:
    togglesignupdate:
        description: Turns sign updating on or off
        usage: /togglesignsupdate
    reloadsignlink:
        description: Reloads the variable values in values.yml
        usage: /reloadsignlink
    variable:
        description: Handles variables
        usage: See development page
        aliases: [var]